// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeT2FDXMDVUgIx8BF7szchjBO5PjFsFUA',
    appId: '1:744380834306:android:260296bd7aee892b083d1b',
    messagingSenderId: '744380834306',
    projectId: 'mossorotaxi-c7365',
    databaseURL: 'https://mossorotaxi-c7365-default-rtdb.firebaseio.com',
    storageBucket: 'mossorotaxi-c7365.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOK4egRoXxcfz3aQkYY1V1AuSPUChB_zA',
    appId: '1:744380834306:ios:32b40767af559ca9083d1b',
    messagingSenderId: '744380834306',
    projectId: 'mossorotaxi-c7365',
    databaseURL: 'https://mossorotaxi-c7365-default-rtdb.firebaseio.com',
    storageBucket: 'mossorotaxi-c7365.appspot.com',
    iosClientId:
        '744380834306-jqf6qgpu10g4lh9173dpvevrg6hpf3n8.apps.googleusercontent.com',
    iosBundleId: 'br.com.prefeiturademossoro.mossorotaxi',
  );
}
